# Désactiver la compilation incrémentale
kotlin.incremental=false
kotlin.parallel.tasks.in.project=false

# Désactiver le cache des classes Kotlin
kotlin.caching.enabled=false

org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
