// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsHmxwClb-_vKIjlyoBpep9wdJfxeexq4',
    appId: '1:201108191364:web:7f7dba11039caaa0b72ad1',
    messagingSenderId: '201108191364',
    projectId: 'devcommunity-chat',
    authDomain: 'devcommunity-chat.firebaseapp.com',
    storageBucket: 'devcommunity-chat.firebasestorage.app',
    measurementId: 'G-QJ5MN6SXXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDufe_iRWksDA7Sahzipij838hbFvIzViw',
    appId: '1:201108191364:android:7eda51a7888ada16b72ad1',
    messagingSenderId: '201108191364',
    projectId: 'devcommunity-chat',
    storageBucket: 'devcommunity-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv44cXU04ScLeLBAq_qeohbAtUxrOrjGI',
    appId: '1:201108191364:ios:4a8b3ae369183dbdb72ad1',
    messagingSenderId: '201108191364',
    projectId: 'devcommunity-chat',
    storageBucket: 'devcommunity-chat.firebasestorage.app',
    iosBundleId: 'com.devcommunity.devcommunitychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv44cXU04ScLeLBAq_qeohbAtUxrOrjGI',
    appId: '1:201108191364:ios:4a8b3ae369183dbdb72ad1',
    messagingSenderId: '201108191364',
    projectId: 'devcommunity-chat',
    storageBucket: 'devcommunity-chat.firebasestorage.app',
    iosBundleId: 'com.devcommunity.devcommunitychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsHmxwClb-_vKIjlyoBpep9wdJfxeexq4',
    appId: '1:201108191364:web:7ede5c9e40914403b72ad1',
    messagingSenderId: '201108191364',
    projectId: 'devcommunity-chat',
    authDomain: 'devcommunity-chat.firebaseapp.com',
    storageBucket: 'devcommunity-chat.firebasestorage.app',
    measurementId: 'G-QCK5GFL2GS',
  );
}
